- index.html
This took me a while to understand.
> Clarify "Module Initialization" example on homepage

- css/style.css
- getting-started.html
- index.html
- repl.html
Just lists the basic installation instructions, API usage and options.
> Add docs page with basic CLI and API usage

- js/repl.js
Avoids issues like https://github.com/facebook/prepack/issues/515
> Add a warning when REPL code is completely dead code

- package.json
> Update package.json engines field

- src/intrinsics/ecma262/Map.js
- src/serializer/serializer.js
- test/serializer/basic/Map2.js
- test/serializer/basic/Set.js
- test/serializer/basic/WeakMap.js
- test/serializer/basic/WeakSet.js
Map, Set, WeakMap and WeakSet can now be serialized.
> Serializer support for maps and sets

- index.html
> Adding back words accidentally removed by another pull request.

- src/options.js
- src/prepack-cli.js
- src/types.js
Fixes: https://github.com/facebook/prepack/issues/571
> cli: parse compatibility argument

- src/prepack-node.js
First step for https://github.com/facebook/prepack/issues/517
> changing to logging for future piping.

- README.md
> Added usage instructions and link to API page #602

- getting-started.html
updated the footer with the same syntax as the index.html
> Updated the footer

- src/serializer/serializer.js
There's still another TODO regarding #22 left in the code. I added a repro for what's still to be implemented in the description of that task.
> Removing outdated TODO.

- .eslintrc
- scripts/test-runner.js
- src/intrinsics/dom/global.js
- src/utils/generator.js
- test/serializer/basic/setTimeout2.js
- test/serializer/basic/setTimeoutAndInterval.js
Added test.
This addresses #20, and helps with #626.
> Implement global.setTimeout and global.setInterval.

- src/evaluators/ForInStatement.js
- test/serializer/abstract/ForInStatement12.js
Identified a number of possible issues, leaving behind some TODOs.
Adding test created by Chris.
> Fixing deficiency in abstract For-In treatment.

- src/evaluators/ForInStatement.js
A for-in loop that copies properties from a simple partial object to another object, can be allowed only if the target object is also marked as as simple and partial, following the loop.
If the source object the simple assignment in the loop body is the same as the for-in object, then
the own enumerable properties of the source object can be copied to the abstract state of the target object.
This reworks pull request #631.
> Make target object of abstract for-in loop simple and partial

- src/evaluators/UpdateExpression.js
- test/serializer/abstract/UpdateExpression.js
- test/serializer/abstract/UpdateExpression2.js
- test/serializer/abstract/UpdateExpression3.js
This is one take on it. I tried to unify with the logic below but couldn't really think of a clever structure.
Fixes #594
> Implement Abstract UpdateExpression

- src/evaluators/LogicalExpression.js
Make logical expressions look more like conditional expressions and handle possibly normal completions from the second operand.
> Cleanup partial evaluation of logical expressions

- src/completions.js
- src/environment.js
- src/methods/call.js
> Remove unused ComposedAbruptCompletion

- scripts/test262-runner.js
My first take at: https://github.com/facebook/prepack/issues/472
to have it only skip on circle I was thinking of checking for an environment variable:
`if(process.env.CIRCLECI)`
based on https://circleci.com/docs/1.0/environment-variables/
If I'm way off base of what was expected, I'll be happy to rewrite if someone can point me in the correct direction.
> [WIP] initial skipping tests

- package.json
- scripts/test262-runner.js
We are still seeing time-outs.
> Add yet another test to time out list.

- scripts/test262-runner.js
> Add yet another test to timeout list

- src/options.js
- src/prepack-cli.js
- src/serializer/serializer.js
My first attempt at: https://github.com/facebook/prepack/issues/413
I'm not sure if all of the console.time's are in the correct spots.
From the issue, I don't know where to find: How long does speculative initialization of more modules take?
> [WIP] Profiling of phases

- js/repl.js
Add 2 examples from https://prepack.io front page.
I will add the other examples as well if this changes look good to you.
> Add all prepack.io frontpage examples to prepack.io/repl.html

- css/style.css
- js/repl-worker.js
- js/repl.js
- repl.html
This should complete work for: #958 
Made it easy to add new options down the line.
**Preview**
> adding options menu on prepack.io/repl.html

- js/repl.js
- repl.html
https://github.com/facebook/prepack/issues/957
> Make code in prepack.io/repl.html sharable

- js/repl.js
Adds an option to enable JSX support to the website's REPL
> Adds JSX support to website REPL
