- src/methods/join.js
- src/values/AbstractValue.js
- src/values/ConcreteValue.js
- test/serializer/abstract/PutValue13.js
This resolves issue #499.
ValuesDomain.topValue occurs in abstract values that should not be treated as possibly deleted, but neither should joining Empty with Top result in a value that is treated as not possibly deleted.
Consequently there is now an additional field in AbstractValue that tracks the possibly deleted status of an abstract value.
Quick reminder on "possibly deleted": If we join a branch where a property exists with a branch where it is deleted, the joined abstract value stored in that property has to reflect that there is a branch where the property does not exist, so that any checks for its existence become conditional.
> Use a separate domain for tracking might be deleted

- src/methods/abstract.js
I think firstly, d and e should be comparing `x.value` to ±`0` (rather than x itself).
But I think these are then redundant, since c handles this for us. Sorry if I'm wrong on this!
> Remove Redundant Code in Strict Equality

- getting-started.html
There's a typo on Getting Started Page as well as the Module Initialization scrollbar didnt align (drove me nuts), this should fix it.
> Fixes typo on Getting started page

- src/evaluators/ForInStatement.js
- src/serializer/serializer.js
- src/values/ObjectValue.js
- test/serializer/abstract/ForInStatement2a.js
- test/serializer/abstract/GetValue7.js
- test/serializer/abstract/GetValue8.js
Fixes Issue #486.
The problem was that defaulting to a member expression reading from the underlying object does not work unless the object is partial (i.e. obtained from the outside world).
Since we know all of the writes to a non partial object, it suffices to put undefined at the end of the chain of comparisons of the unknown property value to previously written known and unknown property names.
Fixing this invalidated an invariant in emitResidualLoopIfSafe, so that code now has a check rather than an invariant.
> Fix GetPartialValue for non partial objects

- src/options.js
- src/prepack-node.js
- src/prepack-standalone.js
To catch typos in options. I had to be a bit clever here to trick Flow into letting me create an empty object as the default.
> Make Options an exact type

- src/utils/generator.js
- test/serializer/basic/IntrinsicPutValue.js
This used to encode it as `Object.0 = 1;`
> Encode invalid identifiers (such as "0") as computed string expressions

- scripts/generate-sourcemaps-test.js
- scripts/test-internal.js
- scripts/test-runner.js
- src/options.js
- src/prepack-node.js
- src/prepack-standalone.js
- src/serializer/serializer.js
- src/types.js
This gives us some better end-to-end coverage and makes it easier move internals around.
This surfaced a few bugs/issues in the API.
I left the thing that detects introspection errors but this surfaced that we don't have a way to pass custom error loggers through the public API. I didn't want to expose the whole Realm and Value types externally. It might be worth having a string based way to get logs in the future though.
> Use public APIs in tests

- css/prism.css
- css/style.css
- index.html
Fixes #555. Continuation of #560 by @solodynamo.
Uses flexbox to make the code sample input and output boxes the same height.
The elements in this screenshot have borders just to show that everything is lined up nicely.
This didn't effect anything on the getting started page.
And here is a screenshot the way it actually is (with the scrollbar visible for proof).
> Fix code sample height with scrollbars

- src/serializer/serializer.js
- test/serializer/basic/RegExp.js
Use a literal expression instead of a call expression and do not set lastIndex to its default value.
Addresses issue #579.
> Make serializer smarter about regular expression literals

- src/serializer/serializer.js
- src/utils/generator.js
- src/values/AbstractObjectValue.js
- test/serializer/abstract/DeleteArrayProperty2.js
- test/serializer/abstract/GetValue9.js
Use a single method to check if a property name is a valid identifier and generate the appropriate Babel node for use in a MemberExpression.
Addresses issue: #581
> Check if member expression property name is a valid id

- circle.yml
As discussed with @NTillmann...
The purpose of this is to be able to land #397 with some test coverage. In its current form it is too specific in its implementation and only works on a specific version of Node. In the future we'll want to make that more abstract and general so that it can work on ranges and other major versions.
I have noticed that this version had some Test262 timeouts on my machine. We might need to tweak them if CI starts being flaky.
> Update Circle CI Node Version to 7.9.0

- src/serializer/modules.js
Factoring out tryInitializeModule from initializeMoreModules in order to prepack individual modules.
Made delayUnsupportedRequires feature less fragile by prepacking in time modules by are
known to be transitively required by unsupported require calls.
Also adding a big comment which starts to describe what's conceptually problematic with the delayUnsupportedRequires feature.
Tested and verified on big manual integration test. Unit test is still missing, as I have to board an airplane... Maybe Chris can fill that in? His flight is an hour later :-)
> Improving delayUnsupportedRequires feature

- src/serializer/serializer.js
- test/serializer/basic/RegExp.js
This change does not properly take into account `/` inside of strings passed to the RegExp constructor.
Test creating a regexp on `/\/+/g` and `"a/b"`.
> Revert 582 regexp

- src/intrinsics/index.js
- test/serializer/basic/IteratorPrototype.js
- test/serializer/basic/MapIteratorPrototype.js
Kind of abusing the intrinsic string name here but that's ok for now.
Fixes #608
> Encode IteratorPrototypes as Intrinsic Names

- js/repl.js
As mentioned in #604
This highlights the erroneous line (when the link is clicked, of course) in the case of an Error.
I have used `red` color to show the link, is that all right?
Here's how it looks: 
Clicking on the link **highlights** that particular line in the `editor`.
> Adds navigation to error line on repl.html #604

- js/repl.js
Currently, due to a mistake in my last pull request, the error highlighting only works if the line number is a single digit number. (I was using `slice(0,1)` :laughing: ). This is a fix for that sorcery. :tada:
> Fix REPL Error highlighting

- src/methods/join.js
- src/realm.js
- src/utils/generator.js
- test/serializer/abstract/Return7.js
If control can leave a block in more than one way, then additional work is needed to come up with the effects of the block if it is evaluated by partially_evaluate.
Fixing this also showed up an incompleteness in the logic for joining completions. Adding more functionality to the joining logic makes up the bulk of the changes in this request.
This addresses issue #596.
> Allow possibly normal completions inside abstract conditional code

- src/evaluators/CallExpression.js
- src/intrinsics/prepack/global.js
- src/methods/join.js
- test/serializer/abstract/Call.js
- test/serializer/abstract/Call2.js
- test/serializer/abstract/Call3.js
Abstract functions that arise from joining concrete functions because of an abstract condition can be invoked at prepack time, provided that their effects are joined together. I.e. it much like calling the two functions from the two different branches of an if statement.
This addresses issue: #437
> Inline calls of abstract functions created from known functions

- css/style.css
Right now, main `nav` looks quite dead because there are no interactions on hover.
I added a border so that there's at least some visual feedback.
An alternative would be to set `color: white` on hover instead (adding both is perhaps too much).
> show nav item border on hover

- scripts/test262-runner.js
The test's file names start with S, but their es5ids do not, so they were not being excluded from the tests to run with a short timeout.
> Remove S prefix that is absent from es5id

- package.json
- src/prepack-cli.js
Builds on top of #653
This lets us prepack Prepack itself using the node-cli option. Added a yarn shortcut to run it with the required flags.
Just for fun.
> Leave a residual function in prepack-cli

- css/style.css
- frequently-asked-questions.html
- getting-started.html
- index.html
- js/toggle_menu.js
- repl.html
Hello,
This is my first pull request, if I did something wrong please say it to me !
I add a basic mobile navigation to the website to access easily all the html pages.
I change all the nav part in style.css, add a toggle-menu.js where I have an eventListener to click on a hamburger menu icon, add the html part in each html file and add the script src at the bottom.
//edit
The second commit correct a display error in repl.html (the record container was hidden outside an element)
And of course I only see after doing this pull request that the navigation on mobile is good. It's just a little buggy when you resize on a browser (or using sizzy app)
> add mobile navigation

- src/methods/call.js
- test/serializer/abstract/Call4.js
Makes the following pass:
```js
__assumeDataProperty(global, "func", __abstract("function"))
[1].map(func)
```
> Support non-direct calls of abstract functions

- scripts/test262-runner.js
After updating my node from 6.10 to 7.10, I'm seeing some timeouts on my laptop, so I'm adding those to the exclusion list.
Strangely, I also see my laptop running fewer tests that seem to run on the CircleCI server. For now, I'm lowering the expected number of tests that should pass to match my laptop.
> Exclude more tests that time out

- src/serializer/serializer.js
- src/serializer/types.js
- test/serializer/basic/RecursiveMutatedFunctionIdentifier.js
This is needed in case of recursive dependencies.
Adding test.
This addresses #570.
> Set up binding identity before starting to serialize value.

- src/serializer/serializer.js
- test/serializer/basic/EfficientPrototypeSetting.js
- test/serializer/basic/NonObjectPrototypes.js
- test/serializer/basic/NullPrototype.js
When an object of kind Object needs its __proto__ property configured, don't set it directly; instead, use an auxiliary constructor.
Adding test.
This addresses #574.
> Avoid setting __proto__ directly when possible

- package.json
- src/evaluators/CallExpression.js
- src/intrinsics/node/contextify.js
- src/intrinsics/node/process.js
- src/methods/date.js
- src/serializer/modules.js
- src/utils/generator.js
Flow now points out when a call site supplies unexpected arguments. Removed such cases from our code.
> Update Flow version, fix new Flow errors

- src/evaluators/CallExpression.js
- src/evaluators/ForInStatement.js
- src/evaluators/IfStatement.js
- src/evaluators/LogicalExpression.js
- src/methods/call.js
- src/methods/function.js
- src/realm.js
- src/serializer/logger.js
- src/serializer/modules.js
partially_evaluate is a bit of a misnomer, so renamed it to evaluateForEffects. While at it, also renamed all of the related methods to follow camlCase conventions.
> Rename Realm methods dealing with effects tracking

- src/completions.js
- src/methods/join.js
Since every completion has a value the value for a PossiblyNormalCompletion may as well be deterministic and useful. Note that there may be many abrupt completions folded into a PossiblyNormalCompletion, but there is only one normal completion, so that is the completion that determines the value of the composite.
> Make sure PossiblyNormalCompletion.value is the normal value

- src/prepack-cli.js
- src/prepack-node.js
The callback invocation in prepackFile was passing a redundant 'null' as
the first argument of the invocation rather than passing the serialized
data as the sole argument, which is what the callback expects.
As a result, calling prepackFile would fail with an exception.
Solution: remove the leading 'null' argument
> Bug fix: Callback invocation in prepackFile args

- scripts/test262-runner.js
- src/intrinsics/ecma262/Date.js
Implement most basic Date.parse by using underlying runtime's Date.parse method
> Implement Date.parse

- package.json
- scripts/test-residual.js
- scripts/test262-runner.js
- src/domains/ValuesDomain.js
- src/methods/call.js
- src/methods/function.js
- src/partial-evaluators/BlockStatement.js
- src/partial-evaluators/Identifier.js
- src/partial-evaluators/IfStatement.js
- src/realm.js
- src/values/AbstractObjectValue.js
- src/values/AbstractValue.js
- src/values/BooleanValue.js
- src/values/ConcreteValue.js
- src/values/NullValue.js
- src/values/NumberValue.js
- src/values/ObjectValue.js
- src/values/StringValue.js
- src/values/SymbolValue.js
- src/values/UndefinedValue.js
- src/values/Value.js
- test/residual/If.js
This adds a partial evaluator for if statements. To support this, AbstractValue now has helper methods for determining if ToBoolean(absvalue) is known to always result in false or always result in true. To make it painfully clear that this is 3-valued logic, the pattern of "!mightNotBeTrue" is preferred over the simpler "isTrue".
Realm.stopEffectCapture now also becomes stopEffectCaptureAndUndoEffects because the latter bit is always connected to it anyways.
> Partial evaluator for if statement

- scripts/test-runner.js
- src/serializer/ResidualHeapVisitor.js
- src/serializer/serializer.js
- src/serializer/types.js
- test/serializer/basic/CapturedScope.js
- test/serializer/basic/CapturedScope2.js
- test/serializer/basic/CapturedScope3.js
- test/serializer/basic/CapturedScope4.js
- test/serializer/basic/CapturedScope5.js
- test/serializer/basic/CapturedScope6.js
Addresses #494 
This PR moves initialization of modified values from the global scope to the function as outlined in #494. Opening for discussion, work is still needed here, specifically:
* I try to batch function instances by their modified bindings, but I don't know what the correct way to do that is. For now I'm just doing a straight `===` equality check. @cblappert hinted to me that I might be able to use Babel node references here, but I wasn't quite able to figure that out. 
* Testing - I can definitely add more tests. I was also wondering if there are tests for the serialized output somewhere? Seems like it would be good to test that this doesn't just create the same # of functions as before but w/ extra cruft
* Measurement of improvement - Is there an established way to approach …
> Delay allocation of referentialized values

- src/options.js
Calling a Prepack method without supplying the options parameter should default to running the serializer.
> Make serialize the default option

- .eslintrc
- scripts/test262-runner.js
- src/evaluators/AssignmentExpression.js
- src/evaluators/CatchClause.js
- src/evaluators/ForOfStatement.js
- src/evaluators/ObjectExpression.js
- src/evaluators/VariableDeclaration.js
- src/methods/create.js
- src/methods/destructuring.js
- src/methods/environment.js
- src/methods/function.js
- src/methods/index.js
- src/methods/iterator.js
- src/values/ObjectValue.js
This implements the runtime semantics to get all the tests for the `destructuring-binding` feature to pass. At first that was only sections [13.3.3.5](http://www.ecma-international.org/ecma-262/7.0/#sec-destructuring-binding-patterns-runtime-semantics-bindinginitialization) and [13.3.3.6](http://www.ecma-international.org/ecma-262/7.0/#sec-destructuring-binding-patterns-runtime-semantics-iteratorbindinginitialization) along with other unimplemented supporting sections. However, what I learned is that there are actually two ways to destructure in the spec. One for the variable and argument definitions people are familiar with:
```js
const { x } = { x: 5 };
```
…and another for destructuring an expression which can lead to interesting code which I first did not believe was JavaScript:
```js …
```
> Implement ES6 destructuring bindings

- src/prepack-node-environment.js
- src/prepack-node.js
See discussion in #691 - apparently the previous change was not taking into account node.js conventions and needs to be reverted.
This change is to revert to the correct calling convention + introduce proper flow-typing for the function signature
> Fix callback to fit node.js conventions

- src/serializer/serializer.js
- test/serializer/basic/UndefinedInResidualFunction.js
We used to turn
```js
global.residual = function() { return undefined; }
```
into
```js
(function () {
var _$0 = this;
function _0() {
return _$0.undefined;
}
residual = _0;
}).call(this);
```
Correct, but very annoying. No more!
(Motivated while working on #699 and realizing that when pushing more code into residual functions, strange things happen.)
> Don't expand occurrences of 'undefined' in residual functions.

- scripts/test-error-handler.js
This test spews a lot of useless information to the console. Reduce it.
> Make error handler test less verbose

- src/serializer/serializer.js
- test/serializer/basic/Undefined.js
- test/serializer/basic/UndefinedAsLocalVariableName.js
Similarly to the previous change that resolved 'undefined' in residual functions to 'void 0',
serialize all 'undefined' values as 'void 0' (and avoid using Babel's valueToNode which produces the
ambiguous 'undefined' literal).
Add test case that ensures that we never emit 'undefined',
and another regression test case that used to fail the serializer when using the local variable name 'undefined'.
> Never emit 'undefined' literal.

- src/environment.js
- src/methods/call.js
- src/methods/function.js
- src/methods/join.js
- src/partial-evaluators/BinaryExpression.js
- src/partial-evaluators/CallExpression.js
- src/partial-evaluators/IfStatement.js
- src/partial-evaluators/MemberExpression.js
- src/partial-evaluators/Program.js
- src/realm.js
- test/residual/call.js
- test/residual/call2.js
- test/residual/call3.js
- test/residual/call4.js
- test/residual/call5.js
- test/residual/call6.js
Partially evaluate the function expression and arguments expressions and deal with all the different kinds of abrupt and possibly abrupt completions when determining the abstract state that results from the function.
At this stage, function calls are not inlined in the residual code.
> Partial evaluator for calls

- src/methods/to.js
- test/serializer/abstract/BinaryExpression2.js
Abstract values might be objects, in which case GetToPrimitivePureResultType must return undefined.
> Tighten up test for pure binary expressions

- src/intrinsics/prepack/global.js
- src/serializer/ResidualHeapVisitor.js
- src/values/FunctionValue.js
- test/serializer/abstract/ResidualExplicitParameters.js
- test/serializer/abstract/ResidualExplicitParameters2.js
Added a simple implementation of __residual_unsafe that allows for implicit dependencies for residual functions. I have also added a test case that validates this new feature.
> __residual requires making all dependencies explicit. Have variant that infers them! #622

- scripts/test-error-handler.js
- src/errors.js
- src/evaluators/AssignmentExpression.js
- src/evaluators/BinaryExpression.js
- src/partial-evaluators/AssignmentExpression.js
- src/partial-evaluators/BinaryExpression.js
- src/realm.js
- test/error-handler/BinaryExpression.js
Produce a nicer error message for + operator with abstract values that might be objects of unknown type. Carry on if the error handler requests it (this is useful to point out more than one error at a time).
Tweak the error handler test runner to deal with recoverable errors and provide a way to specify more expected values for error messages.
> First bit of support for error recovery

- src/serializer/serializer.js
Refactored code to avoid unnecessary source code generation. I noticed that the parsing ast into code generation takes about 2000ms so the updated profiling stats are:
[Profiling] Interpreting Global Code: 12133.150ms
[Profiling] Resolving Initial Modules: 2006.665ms
[Profiling] Deep Traversal of Heap: 5004.448ms
[Profiling] Reference Counts Pass: 8972.274ms
[Profiling] Serialize Pass: 10276.123ms
The Reference Counts Pass is much faster without generating code
> No Need To Generate Source Code On First Serialize Pass

- js/repl.js
Render error codes as hyperlinks to the [GitHub wiki](https://github.com/facebook/prepack/wiki/Prepack-diagnostics) in repl.
Fixes issue: #921
> Add links to wiki in repl errors

- js/repl-worker.js
- js/repl.js
Previously, exceptions thrown by workers and caught by the online REPL were handled by effectively posting no message to the UI, as the `data` component of the message was an empty array. We can instead post string data: the thrown error's `message` property if it's non-empty, or a generic message otherwise.
> Show message for thrown errors on site repl.html (fixes #985)

- src/serializer/Referentializer.js
- src/serializer/ResidualFunctions.js
- src/serializer/ResidualHeapVisitor.js
- src/serializer/types.js
- src/utils/generator.js
- test/serializer/additional-functions/possible_throw_object_assign.js
- test/serializer/additional-functions/return-or-many-throw.js
- test/serializer/additional-functions/return-or-multiple-throw.js
- test/serializer/additional-functions/return-or-throw-modifybindings2.js
- test/serializer/additional-functions/return-or-throw-modifybindings3.js
The additional functions refactor temporarily broke updating modified bindings more than once. This is a more principled solution to that problem that involves emitting the update to the modified binding as the generator entry is encountered instead of after-the-fact in the ResidualFunctions file. This is now possible because of a previous refactor pulling the referentialization logic to happen earlier in serialization.
Makes progress towards #1087 with being able to serialize multiple modifications to the same variable now for that, we just need to automatically make captured variables abstract or intrinsic so that their updates are serialized out correctly (without assuming their concrete value).
Seems to also fix serializing PossiblyNormalCompletions with nested …
> Update how modified bindings are serialized

- src/realm.js
- src/serializer/functions.js
Release Notes: None
Effects should only ever be applied once unless they're applied in the context of `withEffectsApplied` which ensures that they're reverted properly without destroying part of the `Effects` object.
Also fixes a bug uncovered by this where `_createAdditionalEffects` would destroy the original effects, but the caller would then continue using the original effects instead of the effects returned.
> Verify that Effects are only applied once
